# Generated by Django 5.1.1 on 2024-09-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interest",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
