# Generated by Django 5.1.1 on 2024-09-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_interest_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.ManyToManyField(
                related_name="interests", to="account.interest"
            ),
        ),
    ]
