# Generated by Django 5.1.1 on 2024-09-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="choices",
        ),
    ]
